### Program 2: Slicing in 2D NumPy Arrays

In [1]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix:\n", matrix)
print("First Row:", matrix[0])
print("Second Column:", matrix[:, 1])
print("Sub-matrix:\n", matrix[0:2, 1:3])


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First Row: [1 2 3]
Second Column: [2 5 8]
Sub-matrix:
 [[2 3]
 [5 6]]
